from typing import Hashable, Optional, List, Iterable
from collections import defaultdict
# print(defaultdict)

class Graph:
    """Graph Class and Outline"""

    def __init__(self, directed: bool = False): ...
    def add_vertex(self, v: Hashable) -> None: ...
    def add_edge(self, u: Hashable, v: Hashable, weight: Optional[float] = None): ...
    def get_neighbours(self, v: Hashable) -> List[Hashable]: ...
    def __len__(self) -> int: ...
    def bfs(self, start: Hashable) -> Iterable[Hashable]: ...

